language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without benchmarks
script:
  - bundle exec rake spec
  - bundle exec rubocop
after_success:
  - '[ "$TRAVIS_RUBY_VERSION" = "2.3.1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.1.5.0
  - ruby-head
  - rbx-3
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
before_install:
  - gem update bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  include:
    - rvm: jruby-head
      before_install: gem install bundler --no-ri --no-rdoc

notifications:
  email:
    recipients:
      - fg@flashgordon.ru
    on_success: change
    on_failure: always
    on_start: false     # default: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
